sudo: required
language: c
services:
- docker
before_install:
- docker pull tg9541/docker-sdcc:V1.0.1
install:
- docker run -v `pwd`:/home tg9541/docker-sdcc:V1.0.1 /bin/sh -c "sdcc --version ;
  sstm8 -version"
script: docker run -v `pwd`:/home tg9541/docker-sdcc:V1.0.1 /bin/sh -c "cd /home &&
  make simload && make zip"
deploy:
  provider: releases
  api_key:
    secure: ZNnbetCPLBse/7UuVXNLiD8DFXrABWG13H+8ZT0FCJvfZQvLsyaL7q+ziqvgmgAKuw4hD9KKbSsrx++38uybB5juKjXjkfyBr4AWCXOUuSy7ONAFwfWDMbpvgVOyNTOUfaFFV7l/NXcXv2A/oQzD/aFDDrcVSqy9+99uirRV2jhyPtm5vnn73pJmhP9pyRhulSpsKswBhqdadQwGXeDb9sdbHw4B56RvmDvKNENyEfLkakQBzxP/psi94FNJblKfJ2Cl7FLwpuIfKtSeMtPmH4zMyN8zbrAiBZQOjS+MkMJR1LecYZi3St5gtSBOKbcIt9vWCTRfA3Klg1uamipUjObIIHqiGQMykbC/C1Ecv3L/lVpCojFetAkgy3Q/TINbDzApmIVeQfuKgWQkDtUuTeZr3nfdiU287yeKGhpm8Nksu/YYpL6VrXeV7vKrqWio+YIE+Z2jKAc7d55LQuBAaVU3tIcmdGEcFwJq5g5hhE6F3s01pW+JsQ7OQL0NXxfiBM/BOpNZJZ9a252TTl91X7eUrFZlRrMqyrCmO7KubX2FU+2Y3g0X9pFWgv9RYFYSmmcyCrHyVRnhPM47GThRmET+hhajix9alaKNj1cMW1Zb4/W2eUuUyf5vpOXrahrXAT2lMgnlY9pmSi3ztumNdzbYy5hH3B5Se8KOILroN1c=
  file: MINDEV-forth.zip
  on:
    repo: TG9541/stm8ef-nRF24L01
